= Introduction

== Contexte et Problématique
La préservation et la surveillance de la qualité de l'eau constituent aujourd'hui des enjeux écologiques et sanitaires majeurs. Dans la région de Genève, le suivi de l'état des cours d'eau nécessite une observation rigoureuse pour détecter rapidement diverses formes de pollution, telles que l'apparition soudaine de limon, une coloration anormale de l'eau ou la présence de mousse chimique. Pour répondre à ce besoin, un réseau d'appareils photo a été déployé de manière stratégique sur les berges de plusieurs rivières locales. Ces caméras capturent des images à un intervalle régulier de cinq minutes, générant ainsi des séries temporelles (timelapses) denses, avec un volume atteignant rapidement plusieurs dizaines de milliers de clichés par site de mesure.

Si cette méthode d'acquisition permet une surveillance continue, elle déplace le problème vers la phase d'analyse. À ce jour, ces immenses volumes de données sont labellisés et triés manuellement par des experts environnementaux. Ce processus est non seulement chronophage et fastidieux, mais il souffre également d'un manque de standardisation. Les méthodes de labellisation actuelles ne sont pas structurées de manière uniforme : la nomenclature des fichiers varie, les formats de métadonnées sont hétérogènes, et la ségrégation entre les images "propres" et "polluées" n'est pas optimisée pour un traitement informatique à grande échelle.

Face à ce goulot d'étranglement, l'utilisation de l'apprentissage profond (Deep Learning) et de la vision par ordinateur (Computer Vision) s'impose comme une évidence. Ce projet de Master est né de la nécessité de répondre à ces problématiques en automatisant la détection des pollutions tout en repensant intégralement la gestion de la donnée.

== Objectifs et Démarche Algorithmique
L'objectif premier de ce projet consiste à entraîner un modèle d'Intelligence Artificielle capable de classifier automatiquement l'état des cours d'eau à partir des images capturées. L'idée de départ s'est appuyée sur l'utilisation de réseaux de neurones convolutifs (CNN) de pointe, et plus particulièrement l'architecture `EfficientNet_V2_M`, reconnue pour son excellent compromis entre précision d'extraction des caractéristiques (features) et légèreté de calcul.

Cependant, le passage de la théorie à la pratique a soulevé plusieurs défis inhérents à l'imagerie environnementale en milieu ouvert (in the wild). La nature des données est sujette à de fortes variations : changements de luminosité, cycle jour/nuit, reflets du soleil, et différences topographiques d'une rivière à l'autre (Domain Shift). Pour y faire face, diverses méthodes ont été explorées et testées tout au long du projet :
- *L'Adaptation de Domaine (Domain Adaptation) :* Nous avons expérimenté l'intégration d'une couche d'inversion de gradient (Gradient Reversal Layer - GRL) pour forcer le modèle à extraire des caractéristiques indépendantes du site de prise de vue, afin qu'une IA entraînée sur la rivière "A" puisse fonctionner sur la rivière "B".
- *La cohérence temporelle :* Les images étant prises sous forme de séquences, la confiance du modèle brut pouvait se montrer instable (ex: un oiseau traversant l'image générant un faux positif). Nous avons évalué l'utilisation de réseaux récurrents spatio-temporels (comme les BiLSTM) avant de privilégier des solutions de traitement du signal en post-inférence (filtre médian), plus parcimonieuses en ressources matérielles et tout aussi robustes.
- *Le pré-traitement automatisé :* L'implémentation de filtres mathématiques basés sur la luminosité et la variance des canaux RGB a été nécessaire pour détecter et exclure automatiquement les images nocturnes ou capturées en infrarouge, qui faussaient les prédictions.

== Le Fil Rouge du Projet : La création de "WaterWatcher"
Posséder un modèle d'IA performant exécutable dans un simple *notebook* Python (comme Jupyter) est une réussite scientifique, mais ce n'est pas suffisant pour une utilisation concrète sur le terrain par des utilisateurs non-informaticiens. Notre fil rouge, et le défi d'ingénierie principal de ce Master, a été de transformer un script d'inférence brut en un véritable Environnement de Travail (IDE) autonome, robuste et interactif.

L'objectif final était de créer *"WaterWatcher"*, une application de bureau complète pensée pour le paradigme du *Human-in-the-Loop* (l'humain dans la boucle). Concrètement, le projet a nécessité la mise en place d'une architecture logicielle moderne, découpée en microservices :
- *Un Backend (Flask + PyTorch) :* Travaillant en tâche de fond pour ingérer de lourds répertoires d'images, instancier le modèle Deep Learning de manière asynchrone (multithreading) et appliquer les algorithmes de lissage temporel.
- *Un Frontend interactif (HTML/CSS/JS) :* Développé sous la forme d'un tableau de bord (Dashboard) technique. Il permet à l'expert de visualiser les prédictions de l'IA via des graphiques temporels interactifs (intégration de *Chart.js*), d'ajuster dynamiquement le seuil de tolérance de l'algorithme, et de conserver la décision finale en "forçant" manuellement les labels incorrects (Manual Override).
- *Une encapsulation autonome :* Le tout a été packagé pour s'exécuter comme un logiciel natif (via *PyWebView* et *PyInstaller*) fonctionnant aussi bien sous Windows, macOS que Linux, sans exiger la moindre installation de librairies de la part de l'utilisateur.

Enfin, pour répondre au besoin de standardisation et de persistance des données, un système d'écriture de métadonnées EXIF a été développé. Plutôt que de dépendre de fichiers CSV fragiles et facilement égarés, WaterWatcher injecte les scores de l'IA et la validation de l'expert directement dans le code binaire de l'image JPEG.

Ce rapport détaille la construction de ce système de bout en bout, en explorant les impasses rencontrées à chaque jalon, les évaluations des différents modèles testés, et les choix architecturaux qui ont permis d'aboutir à un outil logiciel d'ingénierie prêt au déploiement.
